[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:openvk-client]
command=uvicorn main:app --host 0.0.0.0 --port 1934

[program:openvk-server]
command=openviking-server --config /app/ov.conf --host 0.0.0.0 --port 1933