[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:openvk-client]
command=bash -c 'PYTHONUNBUFFERED=1 uvicorn main:app --host 0.0.0.0 --port 1934 2>&1 | sed -u "s/^/[CLIENT] /"'
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# [program:openvk-server]
# command=bash -c 'PYTHONUNBUFFERED=1 openviking-server --host 0.0.0.0 --port 1933 2>&1 | sed -u "s/^/[SERVER] /"'
# stopasgroup=true
# killasgroup=true
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0