apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openviking.fullname" . }}-ov-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openviking.labels" . | nindent 4 }}
type: Opaque
stringData:
  ov.conf: |
{{ include "openviking.ovConf" . | indent 4 }}
