{{- if eq .Values.role "primary" }}
apiVersion: v1
kind: Service
metadata:
  name: openvk-rw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openviking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app | quote }}
    app.openviking/role: primary
  ports:
    - name: openvk
      port: {{ .Values.service.port }}
      targetPort: 1933
      protocol: TCP
    - name: sidecar
      port: {{ .Values.service.sidecarPort }}
      targetPort: {{ .Values.sidecar.port }}
      protocol: TCP
{{- end }}
