apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vikingdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vikingdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vikingdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vikingdb.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "vikingdb.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          ports:
            - name: vikingdb
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: VIKINGDB_PERSIST_PATH
              value: {{ .Values.persistPath | quote }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistPath }}
              {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
        {{- with .Values.image.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "vikingdb.fullname" . }}
        {{- end }}
